#!/bin/sh
set -e

    CHANGED_FILES="$(git --no-pager diff --name-status --no-color --cached | awk '{ print $2}')"
    CHANGED_KOTLIN_FILES="$(git --no-pager diff --name-status --no-color --cached | awk '$1 != "D" && $2 ~ /\.kts|\.kt/ { print $2}')"

    ./gradlew --quiet detektFormat

    if ! ./gradlew detektAll; then
        exit 1
    fi

    echo "$CHANGED_FILES" | while read -r file; do
    if [ -f $file ]; then
        git add $file
    fi
done
